# Dependabot設定を無効化（謎のプルリクエスト作成を停止）
# version: 2
# updates:
# - package-ecosystem: bundler
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
# - package-ecosystem: github-actions
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
