# inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'

# 自動修正可能なルールを有効化
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

# セキュリティ関連のルール
Security/YAMLLoad:
  Enabled: true

# パフォーマンス関連のルール（rubocop-performance gemが必要）
# Performance/StringReplacement:
#   Enabled: true

# レイアウト関連のルール
Layout/LineLength:
  Max: 120
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
