# fly.toml app configuration file generated for freee-internship on 2025-09-14T11:52:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'freee-internship'
primary_region = 'hkg'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "sh -c 'bundle exec rails db:migrate && bundle exec rails db:seed'"

# 打刻忘れアラートの定期実行設定（15分間隔）
[[cron]]
  schedule = "*/15 * * * *"  # 15分間隔で実行
  command = "bundle exec rails clock_reminder:check_all"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
