# アプリケーション定数設定ファイル
# ハードコーディングされた値を外部化

# 給与管理設定
wage:
  # 時間帯別時給レート
  time_zone_rates:
    normal:
      start_hour: 9
      end_hour: 18
      rate: 1000
      name: '通常時給'
    evening:
      start_hour: 18
      end_hour: 22
      rate: 1200
      name: '夜間手当'
    night:
      start_hour: 22
      end_hour: 9
      rate: 1500
      name: '深夜手当'
  
  # 月間給与目標（103万の壁）
  monthly_target: 1030000
  
  # 給与ゲージの色分け閾値
  gauge_thresholds:
    low: 50
    medium: 80
    high: 90

# 従業員設定
employee:
  # 従業員IDと名前の対応（将来的にfreee APIから動的取得予定）
  name_mapping:
    '3313254': '店長 太郎'
    '3316120': 'テスト 次郎'
    '3317741': 'テスト 三郎'
    '3316116': 'テスト 四郎'

# 認証設定
auth:
  # パスワードポリシー
  password:
    min_length: 8
    require_letters: true
    require_numbers: true
    require_symbols: false
  
  # 認証コード設定
  verification_code:
    length: 6
    expiry_minutes: 10

# メール設定
email:
  # メール送信設定
  sender_name: '勤怠管理システム'
  reply_to: 'noreply@example.com'

# UI設定
ui:
  # デザイン設定
  colors:
    primary: '#ffca28'
    secondary: '#2c2c2c'
    success: '#4caf50'
    error: '#f44336'
    warning: '#ff9800'
    info: '#2196f3'
  
  # レスポンシブ設定
  breakpoints:
    mobile: 600
    tablet: 768
    desktop: 1024

# システム設定
system:
  # デバッグ設定
  debug: false
  
  # ログ設定
  log_level: 'info'
